//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khVSAutomation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutomationsEntities : DbContext
    {
        public AutomationsEntities()
            : base("name=AutomationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblMatrixSwitcher> tblMatrixSwitchers { get; set; }
        public virtual DbSet<tblMatrixSwitcherCommand> tblMatrixSwitcherCommands { get; set; }
        public virtual DbSet<tblOperationStatu> tblOperationStatus { get; set; }
        public virtual DbSet<tblProjector> tblProjectors { get; set; }
        public virtual DbSet<tblProjectorLift> tblProjectorLifts { get; set; }
        public virtual DbSet<tblReleateProjectorAndLift> tblReleateProjectorAndLifts { get; set; }
        public virtual DbSet<tblTelevision> tblTelevisions { get; set; }
        public virtual DbSet<tblTVCommandWhiteList> tblTVCommandWhiteLists { get; set; }
    }
}
