//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khVSAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatrixSwitcher
    {
        public int MatrixSwitcherID { get; set; }
        public string Name { get; set; }
        public string COMPort { get; set; }
        public bool AutoOnOff { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
    }
}
