//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khVSAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOperationStatu
    {
        public int ID { get; set; }
        public string SessionID { get; set; }
        public int StatusID { get; set; }
        public string Description { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
    }
}
